@startuml
if (**haben sie bereits einen Account?**) then (Ja)
:Anmelden;
:Name und Passwort eingeben;
else (nein)
:registrieren;
:name festlegen;
:Spiele festlegen;
:Achievements, Spielzeit und kaufdatum festlegen;
endif
:zugriff auf die Steamlibary;


@enduml
