@startuml
split
   -[hidden]->
   :Spiel anlegen;
   :Datum eingeben;
   :Errungenschaft eingeben;
split again
   -[hidden]->
   :Errungenschaft anlegen;
   :Datum eingeben;
   :Errungenschaft eingeben;
   :Für welches Spiel ist diese Errungenschaft?;
end split
:Errungenschaft zum Spiel hinzugefügt;

@enduml
