@startuml
split
   -[hidden]->
   :Spiel anlegen;
   :Errungenschaft eingeben;
split again
   -[hidden]->
   :Errungenschaft anlegen;
   :Errungenschaft eingeben;
   :Welches Spiel ist diese Errungenschaft für?;
end split

@enduml
