@startuml
skinparam classAttributeIconSize 0

class Schuelerverwaltung{
 -benutzer : Benutzer
 -überprüfeanmeldung ()
 + Schuelerverwaltung ()
 + anmeldung() : void
 - anmeldung(pPassword : String) : void
 + abmeldung() : void
 + zeigeMenue() : void
 + getAngemeldet() : boolean
 + getSchueler() : Schueler
}



class MenueFuehrung{
 - sc : Scanner(System.in)

 +MenueFuehrung()
 +registriere() : Benutzer
 + anmeldung() : String
 + abmeldung() : void
 + zeigeSpiele(pBenutzer : Schueler) : void
 + spielAnlegen() : Fach
 - start() : int
 + speieleigenschaftenAnlegen(pSchueler : Schueler) : void
 + spieleigenschaftenAbfragen() : String
 + zeigeMenue(pSchuelerverwaltung : Schuelerverwaltung) : void
 - breakLine() : void
 }

class Person{
 -vorname: String
 -nachname: String
 -alter : int
 + Person(pVorname : String, pNachname : String, pAlter : int)
 +setVorname(pName : String) : void
 +setNachname(pName : String) : void
 +getVorname() : String
 +getNachname() : String
 +setAlter(pAlter : int) : void
 +getAlter() : int
}



class Spiel{
 -name : String
 +spiel(pName : String)
 +gebeAlleErrungenschaften aus() : String
 +spielzeithinzufügen(pSpielzeit : int) : void
 +getName(): String
 +setName(pName : String) : void
 +toString() : String
}

class Errungenschaft{
 +name : String
 -jahr : int
 +Errungenschaft( pJahr : int ,pName : String)
 +getErrungenschaft(): String
 setName(): String
 +getJahr(): String
 +setJahr(pErrungenschaft : WWrrungenschaft) : void
 +toString() String
}




class Benutzer{
  -passwort : String
  +änderePassword(pPassword : String) : void
  +ueberpruefeAnmeldedaten(pPassword : String, pName : String): boolean
  + SpieleAnlegen(pSpiel : Spiel) : void
  +alleSpieleAusgeben() : void
  +BewertungenFuerSpielAnlegen(pSpieleID : int, pErrungenschaft : String) : void
   +errungenschaftFuerSpielAnlegen(pSpieleID : int, pErrungenschaft : String) : void
  -setPassword(pPassword : String) : void
}

class Datenleser{
  +leseDatenein() : void 
  -leseBewertungenEin : int
  -leseBenutzerDatenEin : String
  -leseErrungenschaftein : String
  -leseSpieleein() : Spiel
  }


Spiel "1" *-- "0..10" Errungenschaft
Schuelerverwaltung  *-- "1" MenueFuehrung
Benutzer "1" *-- "0..10" Spiel
Person <|-- Benutzer

@enduml
