@startuml
skinparam classAttributeIconSize 0

class Benutzerverwaltung{
 -benutzer : Benutzer
 -überprüfeanmeldung ()
 + Benutzerverwaltung ()
 + anmeldung() : void
 - anmeldung(pPassword : String) : void
 + abmeldung() : void
 + zeigeMenue() : void
 + getAngemeldet() : boolean
 + getBenutzer() : Benutzer
}



class MenueFuehrung{
 - sc : Scanner(System.in)

 +MenueFuehrung()
 +registriere() : Benutzer
 + anmeldung() : String
 + abmeldung() : void
 + zeigeSpiele(pBenutzer : Benutzer) : void
 + spielAnlegen() : Spiel
 - start() : int
 + speieleigenschaftenAnlegen(pBenutzer : Benutzer) : void
 + spieleigenschaftenAbfragen() : String
 + zeigeMenue(pBenutzerverwaltung : pBenutzerverwaltung) : void
 
 }

class Person{
 -vorname: String
 -nachname: String
 -alter : int
 + Person(pVorname : String, pNachname : String, pAlter : int)
 +setVorname(pName : String) : void
 +setNachname(pName : String) : void
 +getVorname() : String
 +getNachname() : String
 +setAlter(pAlter : int) : void
 +getAlter() : int
}



class Spiel{
 -kaufjahr : int 
 -name : String
 +spiel(pName : String)
 +gebeAlleErrungenschaften aus() : String
 +spielzeithinzufügen(pSpielzeit : int) : void
 +getName(): String
 +setName(pName : String) : void
 +setKaufjahr:int
 +getKaufjahr(pJahr:int)
 +toString() : String
}

class Errungenschaft{
 +name : String
 -jahr : int
 +Errungenschaft( pJahr : int ,pName : String)
 +getErrungenschaft(): String
 setName(): String
 +getJahr(): String
 +setJahr(pErrungenschaft : Errungenschaft) : void
 +toString() String
}




class Benutzer{
  -passwort : String
  +änderePassword(pPassword : String) : void
  +ueberpruefeAnmeldedaten(pPassword : String, pName : String): boolean
  + SpieleAnlegen(pSpiel : Spiel) : void
  +alleSpieleAusgeben() : void
  +BewertungenFuerSpielAnlegen(pSpieleID : int, pErrungenschaft : String) : void
   +errungenschaftFuerSpielAnlegen(pSpieleID : int, pErrungenschaft : String) : void
  -setPassword(pPassword : String) : void
}

class Datenleser{
  +erstelleDatei()
  +leseDatenein() : void 
  -leseBewertungenEin : int
  -leseBenutzerDatenEin : String
  -leseErrungenschaftein : Errungenschaft
  -leseSpieleein() : Spiel
  +gebeBerwertungAus(): 
  }

class Bewertung{
  +Bewertungspunkte:int
  +pBewertungstext:String
  +setBewertung(pBewertungstext:String,pBewertungspunkte:int)
  +löscheBewertung(pBewertng:Bewertung)

}


Spiel "1" *-- "0..10" Errungenschaft
Spiel "1" *-- "0..10" Bewertung
Benutzerverwaltung  *-- "1" MenueFuehrung
Benutzer "1" *-- "0..10" Spiel
Person <|-- Benutzer

@enduml
