@startuml Objektdiagramm

object "zyklopus:Benutzer" as zyklopus {
vorname = "Jost"
nachname = "Trappmann"
alter = 16
passwort = "123456"
steamlvl = "8"
}


object "csgo:Spiel" as csgo {
kaufjahr = 2016
name = "CS:GO"
abzeichen = "3"
}

object "kaltpizzaesser:Errungenschaft" as kaltpizzaesser {
name = "Kaltpizzaesser"
jahr = 2017
}

object "bewertung:bewertung" as bewertung{
bewertungspunkte = 9/10
Bewertungstext = sehr gut! rush b blyat
}
csgo --o kaltpizzaesser 
zyklopus--|> csgo
csgo --o bewertung
@enduml